# Generated by Django 4.1.7 on 2023-03-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_user',
            field=models.BooleanField(default=False),
        ),
    ]
