# Generated by Django 4.1.7 on 2023-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_staff_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff_user',
            new_name='is_staff_user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
